#!/bin/bash
# M199 (internal): raw HAL poke to set max acceleration of Z.
# Called by m103.ngc, the REMAP target for M103 - do not call M199 directly from g-code, use M103 Pn instead.
max_acceleration=$1
halcmd setp ini.2.max_acceleration $max_acceleration
halcmd setp ini.z.max_acceleration $max_acceleration
exit 0
