/* Autogenerated by /home/cnc/git/linuxcnc/bin/halcompile on Fri Sep  4 18:34:29 2026 -- do not edit */
#include <rtapi.h>
#ifdef RTAPI
#include <rtapi_app.h>
#endif
#include <rtapi_string.h>
#include <rtapi_errno.h>
#include <rtapi_math64.h>
#include <hal.h>

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:lin2rev:Calculate motor angle from position in machine units");
MODULE_INFO(linuxcnc, "pin:scale:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:cmd_in:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:cmd_out:float:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:fb_in:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:fb_out:float:0:out::None:None");
MODULE_INFO(linuxcnc, "funct:_:1:");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_float_t *scale_p;
    hal_float_t *cmd_in_p;
    hal_float_t *cmd_out_p;
    hal_float_t *fb_in_p;
    hal_float_t *fb_out_p;
    double pi_p;
    double s_p;
    int lastq_p;
    int q_p;
    int rev_p;
};
struct __comp_state *__comp_first_inst=NULL, *__comp_last_inst=NULL;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    (void)extra_arg;
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_float_newf(HAL_IN, &(inst->scale_p), comp_id,
        "%s.scale", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->cmd_in_p), comp_id,
        "%s.cmd-in", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->cmd_out_p), comp_id,
        "%s.cmd-out", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->fb_in_p), comp_id,
        "%s.fb-in", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->fb_out_p), comp_id,
        "%s.fb-out", prefix);
    if(r != 0) return r;
    inst->pi_p = 3.141592654;
    inst->lastq_p = 0;
    inst->q_p = 0;
    inst->rev_p = 0;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
RTAPI_MP_INT(count, "number of lin2rev");
char *names = ""; // comma separated names
RTAPI_MP_STRING(names, "names of lin2rev");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("lin2rev");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "lin2rev.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        size_t i, j;
        int idx;
        char buf[HAL_NAME_LEN+1];
        const size_t length = strlen(names);
        for (i = j = idx = 0; i <= length; i++) {
            const char c = buf[j] = names[i];
            if ((c == ',') || (c == '\0')) {
                buf[j] = '\0';
                r = export(buf, idx);
                if(r != 0) {break;}
                idx++;
                j = 0;
            } else {
                if (++j == (sizeof(buf) / sizeof(buf[0]))) {
                    buf[j - 1] = '\0';
                    rtapi_print_msg(RTAPI_MSG_ERR,"names: \"%s\" too long\n", buf);
                    r = -EINVAL;
                    break;
                }
            }
        }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef POST_EXPORT
#define POST_EXPORT() static int post_export(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef fperiod
#define fperiod (period * 1e-9)
#undef scale
#undef scale_ptr
#define scale_ptr (__comp_inst->scale_p)
#define scale (0+*__comp_inst->scale_p)
#undef cmd_in
#undef cmd_in_ptr
#define cmd_in_ptr (__comp_inst->cmd_in_p)
#define cmd_in (0+*__comp_inst->cmd_in_p)
#undef cmd_out
#undef cmd_out_ptr
#define cmd_out_ptr (__comp_inst->cmd_out_p)
#define cmd_out (*__comp_inst->cmd_out_p)
#undef fb_in
#undef fb_in_ptr
#define fb_in_ptr (__comp_inst->fb_in_p)
#define fb_in (0+*__comp_inst->fb_in_p)
#undef fb_out
#undef fb_out_ptr
#define fb_out_ptr (__comp_inst->fb_out_p)
#define fb_out (*__comp_inst->fb_out_p)
#undef pi
#define pi (__comp_inst->pi_p)
#undef s
#define s (__comp_inst->s_p)
#undef lastq
#define lastq (__comp_inst->lastq_p)
#undef q
#define q (__comp_inst->q_p)
#undef rev
#define rev (__comp_inst->rev_p)


FUNCTION(_) {
#line 19 "/home/cnc/git/cnc-configs/lin2rev.comp"

s = scale;
if(s == 0){
   s = 1;
}

cmd_out = (cmd_in/s)*2.0*pi;

while(cmd_out < -pi){
   cmd_out += 2.0 * pi;
}

while(cmd_out > pi){
   cmd_out -= 2.0 * pi;
}

q = 0;
if(fb_in > pi/2.0){
   q = 2;
}
if(fb_in < -pi/2.0){
   q = 3;
}

if(q != 0 && q == 3 && lastq == 2){
   rev++;
}

if(q != 0 && q == 2 && lastq == 3){
   rev--;
}

lastq = q;

fb_out = ((fb_in+rev*pi*2.0)*s)/(2.0*pi);
}

static int __comp_get_data_size(void) { return 0; }
